POST http://localhost:3003/api/blogs/ HTTP/1.1
Content-Type: application/json

{
    "title": "REFACTOR_TEST",
    "author": "REFACTOR_TEST",
    "url": "REFACTOR_TEST",
    "likes": 555
}

###
GET http://localhost:3003/api/blogs/ HTTP/1.1

### unknown endpoint test
GET http://localhost:3003/api/blabla/ HTTP/1.1