### Get all blogs
GET http://localhost:3003/api/blogs/ HTTP/1.1
### Get all users
GET http://localhost:3003/api/users/ HTTP/1.1
### unknown endpoint test
GET http://localhost:3003/api/blabla/ HTTP/1.1
### update test
PUT http://localhost:3003/api/blogs/66ca9d0c137ce10e3d41a121 HTTP/1.1
Content-Type: application/json

{
    "title": "UPDATED 3 likes to 300",
    "author": "UPDATED UPDATER",
    "url": "http://up-to-date.url",
    "likes": 300
}
### add user test
POST http://localhost:3003/api/users HTTP/1.1
Content-Type: application/json

{
    "username": "root",
    "name": "admin",
    "password": "root"
}
### login test
POST http://localhost:3003/api/login HTTP/1.1
Content-Type: application/json

{
    "username": "test",
    "password": "test"
}
### blog post test
POST http://localhost:3003/api/blogs HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImRlZSIsImlkIjoiNjZkMmQ3OGY4YThkYjI2ODlhOWU2YjY5IiwiaWF0IjoxNzI1NDEzODI5LCJleHAiOjE3MjU0MTc0Mjl9.ek1_LeHnEUx0HXafztSoZxHEm_o_brnbkW21dMkHw14

{
    "title": "For authorized deletion test",
    "url": "http://deletewith.auth",
    "likes": 11
}
### delete test
DELETE http://localhost:3003/api/blogs/66d4f80a9abd77fc21b42b3f HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3QiLCJpZCI6IjY2ZDJkOTMzNWI4OTE4ZTc0OTNmMDVmYiIsImlhdCI6MTcyNTQxNTUwNiwiZXhwIjoxNzI1NDE5MTA2fQ.jkGsoDv_pWVkFp5j5qGiztl7_3_MGjgRCvrwlP-XeF8